env:
  quick_view: True
  show_tags: True
  show_logs: True
  show_solution_info: True
  note_highlight: True
  start_with_line_numbers: True
window:
  top_edge: 1
  bottom_edge: 1
editor:
  tab_size: 4
